#------------------------------------------------------------------------------#
#   app.yaml                                                                   #
#                                                                              #
#   Copyright (c) 2011, Code A La Mode, original authors.                      #
#                                                                              #
#       This file is part of with-me.                                          #
#                                                                              #
#       with-me is free software; you can redistribute it and/or modify        #
#       it under the terms of the GNU General Public License as published by   #
#       the Free Software Foundation, either version 3 of the License, or      #
#       (at your option) any later version.                                    #
#                                                                              #
#       with-me is distributed in the hope that it will be useful,             #
#       but WITHOUT ANY WARRANTY; without even the implied warranty of         #
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          #
#       GNU General Public License for more details.                           #
#                                                                              #
#       You should have received a copy of the GNU General Public License      #
#       along with with-me.  If not, see <http://www.gnu.org/licenses/>.       #
#------------------------------------------------------------------------------#


application: w-th-me
version: 1
runtime: python
api_version: 1


handlers:

- url: /crossdomain.xml
  static_files: assets/crossdomain.xml
  upload: assets/crossdomain.xml

- url: /humans.txt
  static_files: assets/humans.txt
  upload: assets/humans.txt
  
- url: /apple-touch-icon.png
  static_files: assets/apple-touch-icon.png
  upload: assets/apple-touch-icon.png

- url: /favicon.ico
  static_files: assets/favicon.ico
  upload: assets/favicon.ico

- url: /robots.txt
  static_files: assets/robots.txt
  upload: assets/robots.txt

- url: /_assets
  static_dir: assets

- url: /.*
  script: main.py


skip_files:

# Default stuff:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*

# with-me specific stuff:
- ^(.*/)?.*\.swp$
- ^(.*/)?IGNORE\.txt
